<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_r.ic.ard.os.andoyopmail.com_verified-badge tooltip-info</name>
   <tag></tag>
   <elementGuidId>9bbb818d-2302-46dc-8436-caf153759109</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.verified-badge.tooltip-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='region-email']/div/form/dl/dd/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>verified-badge tooltip-info</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>Confirmed</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;region-email&quot;)/div[@class=&quot;change-email-phone-view&quot;]/form[@class=&quot;verify-form&quot;]/dl[1]/dd[1]/span[@class=&quot;verified-badge tooltip-info&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='region-email']/div/form/dl/dd/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
